-- seed.sql — demo account + sample documents.
--
-- ⚠️ GENERATED by `npm run seed:live`. Do not hand-edit the extraction rows:
--    they are real Claude output, captured so the demo shows genuine
--    extraction accuracy rather than numbers someone typed. Regenerate with
--    seed:live if the samples or the prompt change.
--
-- Model: claude-sonnet-5   Captured: 2026-08-17
--
-- Demo login: demo@trueline.app — use the one-click button; the password
-- lives in .env.local as DEMO_PASSWORD and is never sent to the browser.
--
-- Idempotent: deleting the user cascades to documents and extractions.
-- No BEGIN/COMMIT: migrate.mjs wraps this. By hand: psql -1 -f.

DELETE FROM users WHERE email = 'demo@trueline.app';

INSERT INTO users (id, email, password_hash) VALUES (
  '00000000-0000-4000-8000-000000000001',
  'demo@trueline.app',
  'scrypt$16384$8$1$lpfYInVlHToo74dUJrgP2g==$IO1CmBjvXwzlND8gGp9AkCQSnhxRRWzv4kKbQINBkrl0gCnHxpS23/VEBcmt2NcRM0A6d1wBjiag8xNe/vA6fQ=='
);

-- 1. Harbourline Print Co. — clean invoice — should reconcile, no flags
--    no flags
INSERT INTO documents (id, user_id, filename, mime_type, size_bytes, page_count, storage_path, status, attempts, created_at)
VALUES (
  '10000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001',
  'sample-01-clean-invoice.pdf', 'application/pdf', 2968, 1,
  'documents/10000000-0000-4000-8000-000000000001/sample-01-clean-invoice.pdf', 'approved', 1, now() - interval '4 days'
);

INSERT INTO extractions (id, document_id, data, confidence, validation_issues, model, effort, input_tokens, output_tokens, created_at)
VALUES (
  '34dbf226-81c4-421c-a21c-a94a61c450b1', '10000000-0000-4000-8000-000000000001',
  '{"currency":"GBP","due_date":"2026-09-13","subtotal":753,"tax_rate":20,"issue_date":"2026-08-14","line_items":[{"quantity":500,"line_total":420,"unit_price":0.84,"description":"A5 saddle-stitched brochures, 250gsm","line_number":1},{"quantity":4,"line_total":74,"unit_price":18.5,"description":"Business cards, matt laminate (box of 250)","line_number":2},{"quantity":2,"line_total":124,"unit_price":62,"description":"Roll-up banner, 850mm x 2000mm","line_number":3},{"quantity":3,"line_total":135,"unit_price":45,"description":"Artwork amends (hourly)","line_number":4}],"tax_amount":150.6,"vendor_name":"Harbourline Print Co.","total_amount":916.1,"document_type":"invoice","vendor_tax_id":"GB 418 2290 55","invoice_number":"HL-2026-0431","payment_method":null,"service_charge":null,"vendor_address":"Unit 7, Riverside Works, Bristol BS1 6QT, United Kingdom","discount_amount":null,"shipping_amount":12.5}'::jsonb,
  '{}'::jsonb,
  '[]'::jsonb,
  'claude-sonnet-5', 'medium@2026-08-17.1', 2020, 450, now() - interval '4 days'
);

-- 2. Acme Corp — line items disagree with printed subtotal
--    conflict: subtotal
INSERT INTO documents (id, user_id, filename, mime_type, size_bytes, page_count, storage_path, status, attempts, created_at)
VALUES (
  '10000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000001',
  'sample-02-mismatch-invoice.pdf', 'application/pdf', 2326, 1,
  'documents/10000000-0000-4000-8000-000000000002/sample-02-mismatch-invoice.pdf', 'needs_review', 1, now() - interval '3 days'
);

INSERT INTO extractions (id, document_id, data, confidence, validation_issues, model, effort, input_tokens, output_tokens, created_at)
VALUES (
  '0368250f-c018-44d3-a294-86066f2786c5', '10000000-0000-4000-8000-000000000002',
  '{"currency":"GBP","due_date":"2026-09-13","subtotal":1420,"tax_rate":20,"issue_date":"2026-08-14","line_items":[{"quantity":1,"line_total":850,"unit_price":850,"description":"Consulting - Q2 discovery workshop","line_number":1},{"quantity":1,"line_total":390,"unit_price":390,"description":"Technical documentation package","line_number":2}],"tax_amount":284,"vendor_name":"Acme Corp","total_amount":1704,"document_type":"invoice","vendor_tax_id":"GB331902847","invoice_number":"AC-2026-0814","payment_method":null,"service_charge":null,"vendor_address":"88 Union Street, Manchester M1 2AB, United Kingdom","discount_amount":null,"shipping_amount":null}'::jsonb,
  '{}'::jsonb,
  '[{"field":"subtotal","message":"Line items total 1,240.00 but subtotal reads 1,420.00 — 180.00 difference","severity":"conflict"}]'::jsonb,
  'claude-sonnet-5', 'medium@2026-08-17.1', 1875, 317, now() - interval '3 days'
);

-- 3. Blue Ridge Coffee — receipt — service charge, no VAT
--    check: issue_date
INSERT INTO documents (id, user_id, filename, mime_type, size_bytes, page_count, storage_path, status, attempts, created_at)
VALUES (
  '10000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000001',
  'sample-03-receipt.pdf', 'application/pdf', 2182, 1,
  'documents/10000000-0000-4000-8000-000000000003/sample-03-receipt.pdf', 'needs_review', 1, now() - interval '2 days'
);

INSERT INTO extractions (id, document_id, data, confidence, validation_issues, model, effort, input_tokens, output_tokens, created_at)
VALUES (
  '129049fc-5cff-4668-9ac0-95a79d05a283', '10000000-0000-4000-8000-000000000003',
  '{"currency":"GBP","due_date":null,"subtotal":14.3,"tax_rate":null,"issue_date":"2026-04-03","line_items":[{"quantity":2,"line_total":8.4,"unit_price":4.2,"description":"Flat white","line_number":1},{"quantity":1,"line_total":3.8,"unit_price":3.8,"description":"Almond croissant","line_number":2},{"quantity":1,"line_total":2.1,"unit_price":2.1,"description":"Sparkling water 330ml","line_number":3}],"tax_amount":null,"vendor_name":"Blue Ridge Coffee","total_amount":15.52,"document_type":"receipt","vendor_tax_id":null,"invoice_number":"0004821","payment_method":"Visa ending 4412","service_charge":1.22,"vendor_address":"14 Mill Lane, Sheffield S1 4RG","discount_amount":null,"shipping_amount":null}'::jsonb,
  '{"issue_date":0.6}'::jsonb,
  '[{"field":"issue_date","message":"Date 03/04/2026 is ambiguous between DD/MM and MM/DD formats; assumed UK convention (3 April) based on vendor''s UK address.","severity":"check"}]'::jsonb,
  'claude-sonnet-5', 'medium@2026-08-17.1', 1835, 422, now() - interval '2 days'
);

-- 4. Meridian Logistics Pte Ltd — USD, discount + insurance, no due date
--    conflict: due_date
INSERT INTO documents (id, user_id, filename, mime_type, size_bytes, page_count, storage_path, status, attempts, created_at)
VALUES (
  '10000000-0000-4000-8000-000000000004', '00000000-0000-4000-8000-000000000001',
  'sample-04-logistics-invoice.pdf', 'application/pdf', 3102, 1,
  'documents/10000000-0000-4000-8000-000000000004/sample-04-logistics-invoice.pdf', 'needs_review', 1, now() - interval '1 days'
);

INSERT INTO extractions (id, document_id, data, confidence, validation_issues, model, effort, input_tokens, output_tokens, created_at)
VALUES (
  '9bfe2f2c-3f8b-49d4-96ef-17859848d60b', '10000000-0000-4000-8000-000000000004',
  '{"currency":"USD","due_date":null,"subtotal":896.25,"tax_rate":null,"issue_date":"2026-08-17","line_items":[{"quantity":2,"line_total":630,"unit_price":315,"description":"Ocean freight - Colombo to Singapore (2 pallets)","line_number":1},{"quantity":1,"line_total":85,"unit_price":85,"description":"Customs handling and documentation","line_number":2},{"quantity":1,"line_total":47.25,"unit_price":47.25,"description":"Fuel surcharge","line_number":3},{"quantity":4,"line_total":50,"unit_price":12.5,"description":"Container seal and inspection","line_number":4},{"quantity":3,"line_total":84,"unit_price":28,"description":"Warehouse storage (3 days)","line_number":5}],"tax_amount":null,"vendor_name":"Meridian Logistics Pte Ltd","total_amount":889.65,"document_type":"invoice","vendor_tax_id":"SG198203411K","invoice_number":"ML-8830","payment_method":"Wire to DBS Bank, SWIFT DBSSSGSG","service_charge":null,"vendor_address":"12 Keppel Road, #04-11, Singapore 089057","discount_amount":25,"shipping_amount":18.4}'::jsonb,
  '{}'::jsonb,
  '[{"field":"due_date","message":"No due date found — required for invoices","severity":"conflict"}]'::jsonb,
  'claude-sonnet-5', 'medium@2026-08-17.1', 2019, 490, now() - interval '1 days'
);

-- 5. Failed extraction — no extraction row, error reason on the document.
--    Deliberately fabricated: it represents a failure state, not model output.
INSERT INTO documents (id, user_id, filename, mime_type, size_bytes, page_count, storage_path, status, attempts, error_code, error_message, created_at)
VALUES (
  '10000000-0000-4000-8000-000000000005', '00000000-0000-4000-8000-000000000001',
  'scan_20260817_1042.jpg', 'image/jpeg', 3984588, 1,
  'samples/sample-03-receipt.pdf', 'failed', 3,
  'SCHEMA_INVALID',
  'The model''s response did not match the extraction schema after 3 attempts. The scan may be too low-contrast to read.',
  now() - interval '2 hours'
);
