#!/usr/bin/env node
// seed-files.mjs — put the sample document bytes where the seeded rows expect
// them, so the review preview has something to show on the very first click.
//
// This used to copy files into a local .storage directory, which was wrong in
// two ways: the paths did not match what seed.sql records (documents/<id>/…,
// not samples/…), so four of five previews 404'd even locally; and on a
// serverless host there is no persistent disk to copy to at all.
//
// Storage now lives in Postgres, so the seed writes there and works identically
// on a laptop and on Vercel — run `npm run db:seed` against the production
// DATABASE_URL and the deployed demo has its samples.
import { readFile } from "node:fs/promises";
import { basename } from "node:path";
import pg from "pg";

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  console.error("DATABASE_URL is required");
  process.exit(1);
}

const client = new pg.Client({
  connectionString,
  ssl: /sslmode=require|\.neon\.tech/.test(connectionString)
    ? { rejectUnauthorized: true }
    : false,
});

await client.connect();

// The rows are the source of truth for which file belongs where: seed.sql is
// regenerated by `npm run seed:live`, and hard-coding a mapping here is how the
// two drifted apart last time.
const { rows } = await client.query(
  `SELECT id, filename, storage_path FROM documents ORDER BY created_at`,
);

let written = 0;
let missing = 0;

for (const row of rows) {
  // storage_path is documents/<id>/<file>; the bytes come from samples/<file>.
  const source = `samples/${basename(row.storage_path)}`;
  let bytes;
  try {
    bytes = await readFile(source);
  } catch {
    console.warn(`  no source file for ${row.storage_path} (looked for ${source})`);
    missing += 1;
    continue;
  }

  await client.query(
    `INSERT INTO file_blobs (storage_key, bytes, byte_size)
     VALUES ($1, $2, $3)
     ON CONFLICT (storage_key) DO UPDATE SET bytes = EXCLUDED.bytes, byte_size = EXCLUDED.byte_size`,
    [row.storage_path, bytes, bytes.byteLength],
  );
  written += 1;
}

console.log(
  `seeded ${written} file${written === 1 ? "" : "s"} into storage` +
    (missing ? ` (${missing} without a source — run \`npm run samples\` first)` : ""),
);

await client.end();
